packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
minimumReleaseAgeExclude:
  - '@storybook/addon-docs@10.5.1'
  - '@storybook/angular-vite@10.5.1'
  - '@storybook/builder-vite@10.5.1'
  - '@storybook/csf-plugin@10.5.1'
  - '@storybook/react-dom-shim@10.5.1'
  - storybook@10.5.1
  - vite@8.1.5
